# Generated by Django 3.1.6 on 2021-03-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='confirm',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
